In [1]:
import pandas as pd
import numpy as np

In [7]:
date = pd.read_csv('/kaggle/input/datasets/sanjanbm/order-dataset/orders.csv')
time = pd.read_csv('/kaggle/input/datasets/sanjanbm/messages-dataset/messages.csv')

In [8]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [9]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [11]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Dates

In [13]:
date['date'] = pd.to_datetime(date['date'])

date['date'].head()

0   2019-12-10
1   2018-08-15
2   2018-10-23
3   2019-08-17
4   2019-01-06
Name: date, dtype: datetime64[ns]

In [15]:
date.info()

# Now we converted object to datetime object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [17]:
date['date_year'] = date['date'].dt.year

date['date_year']

0      2019
1      2018
2      2018
3      2019
4      2019
       ...
995    2018
996    2018
997    2019
998    2019
999    2019
Name: date_year, Length: 1000, dtype: int32

In [18]:
date.head()

        date  product_id  city_id  orders  year  date_year
0 2019-12-10        5628       25       3  2019       2019
1 2018-08-15        3646       14     157  2018       2018
2 2018-10-23        1859       25       1  2018       2018
3 2019-08-17        7292       25       1  2019       2019
4 2019-01-06        4344       25       3  2019       2019

In [20]:
date['date_month'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  year  date_year  date_month
0 2019-12-10        5628       25       3  2019       2019          12
1 2018-08-15        3646       14     157  2018       2018           8
2 2018-10-23        1859       25       1  2018       2018          10
3 2019-08-17        7292       25       1  2019       2019           8
4 2019-01-06        4344       25       3  2019       2019           1

In [21]:
date['date_month'] = date['date'].dt.month_name()

date.head()

        date  product_id  city_id  orders  year  date_year date_month
0 2019-12-10        5628       25       3  2019       2019   December
1 2018-08-15        3646       14     157  2018       2018     August
2 2018-10-23        1859       25       1  2018       2018    October
3 2019-08-17        7292       25       1  2019       2019     August
4 2019-01-06        4344       25       3  2019       2019    January

In [22]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,year,date_year,date_month,date_day
0,2019-12-10,5628,25,3,2019,2019,December,10
1,2018-08-15,3646,14,157,2018,2018,August,15
2,2018-10-23,1859,25,1,2018,2018,October,23
3,2019-08-17,7292,25,1,2019,2019,August,17
4,2019-01-06,4344,25,3,2019,2019,January,6

In [23]:
# day of week

date['date_dow_name'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,year,date_year,date_month,date_day,date_dow_name
0,2019-12-10,5628,25,3,2019,2019,December,10,1
1,2018-08-15,3646,14,157,2018,2018,August,15,2
2,2018-10-23,1859,25,1,2018,2018,October,23,1
3,2019-08-17,7292,25,1,2019,2019,August,17,5
4,2019-01-06,4344,25,3,2019,2019,January,6,6

In [24]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,year,date_year,date_month,date_day,date_dow_name
0,2019-12-10,5628,25,3,2019,2019,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,2018,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,2018,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,2019,August,17,Saturday
4,2019-01-06,4344,25,3,2019,2019,January,6,Sunday

In [25]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,year,date_year,date_month,date_day,date_dow_name,date_is_weekend
0,2019-12-10,2019,2019,December,10,Tuesday,0
1,2018-08-15,2018,2018,August,15,Wednesday,0
2,2018-10-23,2018,2018,October,23,Tuesday,0
3,2019-08-17,2019,2019,August,17,Saturday,1
4,2019-01-06,2019,2019,January,6,Sunday,1

### 2. Extract week of the year

In [ ]:
date['date_week'] = date['date'].dt.week

date.head()

### 3. Extract Quarter

In [28]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,year,date_year,date_month,date_day,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,2019,December,10,Tuesday,0,4
1,2018-08-15,2018,2018,August,15,Wednesday,0,3
2,2018-10-23,2018,2018,October,23,Tuesday,0,4
3,2019-08-17,2019,2019,August,17,Saturday,1,3
4,2019-01-06,2019,2019,January,6,Sunday,1,1

### 4. Extract Semester

In [29]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,year,date_year,date_month,date_day,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,2019,December,10,Tuesday,0,4,2
1,2018-08-15,2018,2018,August,15,Wednesday,0,3,2
2,2018-10-23,2018,2018,October,23,Tuesday,0,4,2
3,2019-08-17,2019,2019,August,17,Saturday,1,3,2
4,2019-01-06,2019,2019,January,6,Sunday,1,1,1

### 5. Extract Time elapsed between dates

In [30]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 3, 4, 5, 52, 54, 944569)

In [31]:
today - date['date']

0     2276 days 05:52:54.944569
1     2758 days 05:52:54.944569
2     2689 days 05:52:54.944569
3     2391 days 05:52:54.944569
4     2614 days 05:52:54.944569
                 ...
995   2704 days 05:52:54.944569
996   2645 days 05:52:54.944569
997   2493 days 05:52:54.944569
998   2558 days 05:52:54.944569
999   2332 days 05:52:54.944569
Name: date, Length: 1000, dtype: timedelta64[ns]

In [32]:
(today - date['date']).dt.days

0      2276
1      2758
2      2689
3      2391
4      2614
       ...
995    2704
996    2645
997    2493
998    2558
999    2332
Name: date, Length: 1000, dtype: int64

In [ ]:
# Months passed

np.round((today - date['date']) / np.timedelta64(1, 'M'),0)

In [34]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [35]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [36]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [37]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract Time part

In [38]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time difference

In [39]:
today - time['date']

0     4462 days 05:02:54.944569
1     4326 days 06:12:54.944569
2     4812 days 05:31:54.944569
3     4114 days 05:21:54.944569
4     4511 days 06:41:54.944569
                 ...
995   5101 days 05:02:54.944569
996   4422 days 06:38:54.944569
997   4887 days 06:15:54.944569
998   5003 days 06:18:54.944569
999   4275 days 06:27:54.944569
Name: date, Length: 1000, dtype: timedelta64[ns]

In [40]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.855350e+08
1      3.737888e+08
2      4.157767e+08
3      3.554689e+08
4      3.897745e+08
           ...
995    4.407446e+08
996    3.820847e+08
997    4.222594e+08
998    4.322819e+08
999    3.693833e+08
Name: date, Length: 1000, dtype: float64

In [41]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.425583e+06
1      6.229813e+06
2      6.929612e+06
3      5.924482e+06
4      6.496242e+06
           ...
995    7.345743e+06
996    6.368079e+06
997    7.037656e+06
998    7.204699e+06
999    6.156388e+06
Name: date, Length: 1000, dtype: float64

In [42]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107093.048596
1      103830.215262
2      115493.531929
3       98741.365262
4      108270.698596
           ...
995    122429.048596
996    106134.648596
997    117294.265262
998    120078.315262
999    102606.465262
Name: date, Length: 1000, dtype: float64