In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv("/kaggle/input/datasets/sanjanbm/cars-dataset/cars.csv")

df.sample(5)

              brand  km_driven    fuel         owner  selling_price
6499        Hyundai      35000  Diesel   First Owner         500000
7710  Mercedes-Benz      17000  Petrol   First Owner        5200000
4371        Hyundai     120000  Petrol  Second Owner         180000
7599         Maruti      29000  Petrol   First Owner         525000
4147         Toyota      10000  Petrol   First Owner         800000

In [46]:
df.shape

(8128, 5)

In [47]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [48]:
df['brand'].nunique()

32

In [49]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [50]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [51]:
pd.get_dummies(df, columns = ['fuel', 'owner'], dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

## 2. K-1 OneHotEncoding

In [52]:
pd.get_dummies(df, columns=['fuel','owner'], dtype=int, drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

## 3. OneHotEncoding using Sklearn(best method)

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],random_state=42, test_size=0.3)

X_train.shape, X_test.shape

((5689, 4), (2439, 4))

In [54]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

X_test_new = ohe.transform(X_test[['fuel','owner']])

In [55]:
X_train_new.shape

(5689, 9)

In [56]:
X_train[['brand','km_driven']].values

array([['Maruti', 120000],
       ['Toyota', 100000],
       ['BMW', 39000],
       ...,
       ['Hyundai', 35000],
       ['Maruti', 27000],
       ['Maruti', 70000]], dtype=object)

In [57]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new.toarray())).shape

(5689, 11)

## 4. OneHotEncoding with Top Categories

In [58]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [59]:
counts = df['brand'].value_counts()

In [60]:
df['brand'].nunique()
threshold = 100

In [61]:
counts[counts <= threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [62]:
repl = counts[counts <= threshold].index

In [64]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5163,0,0,0,1,0,0,0,0,0,0,0,0,0
5315,0,0,0,0,0,1,0,0,0,0,0,0,0
2642,0,0,0,0,0,0,1,0,0,0,0,0,0
1391,0,0,0,0,0,0,1,0,0,0,0,0,0
4478,0,0,0,0,0,1,0,0,0,0,0,0,0